apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - all.yaml

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: gateway-proxy
    namespace: gloo-system
  spec:
    template:
      spec:
        securityContext:
            sysctls:
            - name: net.netfilter.nf_conntrack_tcp_timeout_close_wait
              value: "10"
