apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - all.yaml

patchesStrategicMerge:
- |-
  apiVersion: gateway.solo.io/v1
  kind: Gateway
  metadata:
    name: gateway-proxy
    namespace: gloo-system
  spec:
    options:
      perConnectionBufferLimitBytes: 104857600
